# CBAM ResNet18 model configuration
# @package _group_

model:
  name: cbam_resnet18
  num_classes: 39 # Number of plant disease classes
  pretrained: true
  freeze_backbone: true # Initially freeze backbone
  dropout_rate: 0.2
  head_type: residual # 'linear' or 'residual'
  hidden_dim: 256
  in_channels: 3
  input_size: [224, 224]
  reduction_ratio: 16 # CBAM channel attention reduction ratio
  feature_fusion: true # Use feature fusion from multiple layers
  use_residual_head: true # Use residual head for classification
  regularization:
    drop_path_prob: 0.1 # Drop path probability

# Override optimizer defaults for this model
optimizer:
  name: adamw
  lr: 0.0001
  weight_decay: 0.01
  differential_lr: true
  differential_lr_factor: 0.1

# Override scheduler defaults for this model
scheduler:
  name: cosine
  min_lr: 0.000001

# Transfer learning settings
transfer_learning:
  enabled: true
  initial_frozen_epochs: 5
  finetune_lr_factor: 0.1
