# General project info
project_name: CBAM Classification
version: 1.0.0

hydra:
  job:
    chdir: true
  output_subdir: null # Don't create .hydra subdirectory with configs
  run:
    dir: .
  sweep:
    dir: "${output_dir}/multirun/${now:%Y-%m-%d_%H-%M-%S}"
    subdir: "${hydra.job.num}"

logging:
  level: INFO
  use_colors: true



  # Simple path configuration without complex interpolation
paths:
  # Base directories - these will be set programmatically
  output_dir: "outputs"
  experiment_name: "cbam_default"
  
  # Data directories - relative to project root
  raw_dir: "data/raw"
  preprocessed_dir: "data/preprocessed"

# Data configuration (rest of your config stays the same)
data:
  dataset_name: PlantDisease
  train_val_test_split: [0.7, 0.15, 0.15]
  random_seed: 42

model:
  name: cbam_only_resnet18 # Model name must match a registered model
  num_classes: 39 # Automatically determined if using get_datasets, but good practice to specify
  pretrained: true # Load pretrained ImageNet weights
  freeze_backbone: false # Initial state (Trainer handles unfreezing)
  feature_fusion: true # Enable feature fusion in backbone
  use_residual_head: true # Use residual head
  dropout_rate: 0.09134925421514478 # Dropout in the head
  input_size: [256, 256] # Expected input image size
  reduction_ratio: 24 # Reduction ratio for CBAM blocks
  regularization: # Regularization within model components (e.g., DropPath)
    stochastic_depth_prob: 0.040397158459940234
    drop_path_prob: 0.19180035377564947


prepare_data:
  output_dir: ${paths.preprocessed_dir}
  dry_run: true
  fix_extensions: true
  verify_images: true
  fix_folders: true
  run_analysis_after_validation: true
  sample_size: 1000
  random_seed: 42
  run_visualization_after_analysis: true
  generate_combined_report: true
  create_plots: true
  n_per_class: 30
  max_classes: null
  create_image_grid: true
  create_tsne: true
  create_clustering: true
  create_similarity: true
  create_augmentation: true
