"""
Visualization tools for model inspection and interpretation.
"""

from .attention_viz import (
    generate_attention_report,
    plot_attention_comparison,
    plot_attention_heatmap,
    visualize_attention_maps,
    visualize_attention_overlay,
    visualize_layer_activations,
)
from .base_visualization import (
    DEFAULT_THEME,
    apply_dark_theme,
    count_model_parameters,
    count_trainable_parameters,
    get_model_size,
    plot_class_metrics,
    plot_confusion_matrix,
    plot_learning_rate,
    plot_model_comparison,
    plot_training_history,
    plot_training_time,
)
from .visualization import (
    create_analysis_dashboard,
    create_augmentation_grid,
    create_classification_examples_grid,
    create_image_grid,
    plot_class_performance,
    plot_confidence_distribution,
    plot_distribution,
    plot_enhanced_confusion_matrix,
    plot_feature_space,
    plot_hierarchical_clustering,
    plot_histogram,
    plot_precision_recall_curve,
    plot_roc_curve,
    plot_scatter,
    plot_similarity_matrix,
    plot_training_curves,
    plot_training_time_analysis,
    plot_tsne_visualization,
    plot_umap_visualization,
    visualize_augmentations,
)

__all__ = [
    # Attention visualization functions
    "visualize_attention_maps",
    "visualize_attention_overlay",
    "visualize_layer_activations",
    "generate_attention_report",
    "plot_attention_heatmap",
    "plot_attention_comparison",
    # Base visualization functions
    "DEFAULT_THEME",
    "apply_dark_theme",
    "count_model_parameters",
    "count_trainable_parameters",
    "get_model_size",
    "plot_class_metrics",
    "plot_confusion_matrix",
    "plot_learning_rate",
    "plot_model_comparison",
    "plot_training_history",
    "plot_training_time",
    # Enhanced visualization functions
    "create_analysis_dashboard",
    "create_augmentation_grid",
    "create_classification_examples_grid",
    "create_image_grid",
    "plot_class_performance",
    "plot_confidence_distribution",
    "plot_distribution",
    "plot_enhanced_confusion_matrix",
    "plot_feature_space",
    "plot_hierarchical_clustering",
    "plot_histogram",
    "plot_precision_recall_curve",
    "plot_roc_curve",
    "plot_scatter",
    "plot_similarity_matrix",
    "plot_training_curves",
    "plot_training_time_analysis",
    "plot_tsne_visualization",
    "plot_umap_visualization",
    "visualize_augmentations",
]
